server:
  port: 8004

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http:127.0.0.1:8001/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: feign
  sensitive-headers:
